aws_region            = "us-east-1"
project_name          = "qloud"
environment           = "dev"
instance_type         = "t3.micro"
aws_access_key_id     = "AKIAYS2NXA5W25XMRM6V"
aws_secret_access_key = "placeholder"
slack_bot_token       = ""